[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
ignore = ["T201", "T203"]
select = [
  "A",
  "ARG",
  "B",
  "BLE",
  "C",
  "DTZ",
  "E",
  "ERA",
  "F",
  "FBT",
  "I",
  "ICN",
  "N",
  "PGH",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RET",
  "RUF",
  "S",
  "SIM",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]

[tool.mypy]
warn_unused_configs = true
warn_unused_ignores = true
show_error_codes = true
warn_unreachable = true
warn_redundant_casts = true
enable_error_code = [
  "redundant-expr",
  "ignore-without-code",
  "truthy-bool",
  "truthy-function",
  "unused-awaitable",
]

strict = true
strict_equality = true
no_implicit_optional = true
no_implicit_reexport = true

# dynamic typing
disallow_any_generics = true
disallow_subclassing_any = true
# disallow_any_expr = true
# disallow_any_decorated = true
warn_return_any = true

# untyped
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
disallow_incomplete_defs = true
check_untyped_defs = true
