[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
select = ["C", "E", "F", "I", "W"]

[tool.mypy]
warn_unused_configs = true
warn_unused_ignores = true
show_error_codes = true
warn_unreachable = true
warn_redundant_casts = true
enable_error_code = [
  "redundant-expr",
  "ignore-without-code",
  "truthy-bool",
  "truthy-function",
  "unused-awaitable",
]

strict = true
strict_equality = true
no_implicit_optional = true
no_implicit_reexport = true

# dynamic typing
disallow_any_generics = true
disallow_subclassing_any = true
# disallow_any_expr = true
# disallow_any_decorated = true
warn_return_any = true

# untyped
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
disallow_incomplete_defs = true
check_untyped_defs = true
